[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"
  publish = "assets"  # This ensures assets are included

[[plugins]]
  package = "@netlify/plugin-functions-core"
  [plugins.inputs]
    include = ["assets/*"]  # Explicitly include assets

[functions]
  node_bundler = "esbuild"