[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"
  publish = "assets"

[functions]
  node_bundler = "esbuild"
  included_files = ["assets/*"]  # Key change - replaces the plugin