[build]
  functions = "netlify/functions"
  command = "echo 'No build needed'"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"